### ISSUE TITLE
윈도우 python -m build 시 에러 발생 - UnicodeDecodeError: 'cp949' codec can't decode byte

### ISSUE THREAD

**Issue by devrokket** [offtheface/infinite-note#5]
```
PS C:\Users\rokan\github\infinite-note> python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=42, wheel)
* Getting dependencies for sdist...
running egg_info
writing manifest file 'src\infinite_note.egg-info\SOURCES.txt'
* Building sdist...
running sdist
running egg_info
writing manifest file 'src\infinite_note.egg-info\SOURCES.txt'
running check
creating infinite_note-0.2.0
creating infinite_note-0.2.0\src
creating infinite_note-0.2.0\src\infinite_note
creating infinite_note-0.2.0\src\infinite_note.egg-info
creating infinite_note-0.2.0\src\infinite_note\file
copying LICENSE -> infinite_note-0.2.0
copying README.md -> infinite_note-0.2.0
copying pyproject.toml -> infinite_note-0.2.0
copying setup.cfg -> infinite_note-0.2.0
copying src\infinite_note\__init__.py -> infinite_note-0.2.0\src\infinite_note
copying src\infinite_note\infinite_note.py -> infinite_note-0.2.0\src\infinite_note
copying src\infinite_note.egg-info\PKG-INFO -> infinite_note-0.2.0\src\infinite_note.egg-info
copying src\infinite_note.egg-info\SOURCES.txt -> infinite_note-0.2.0\src\infinite_note.egg-info
copying src\infinite_note.egg-info\dependency_links.txt -> infinite_note-0.2.0\src\infinite_note.egg-info
copying src\infinite_note.egg-info\entry_points.txt -> infinite_note-0.2.0\src\infinite_note.egg-info
copying src\infinite_note.egg-info\top_level.txt -> infinite_note-0.2.0\src\infinite_note.egg-info
copying src\infinite_note\file\__init__.py -> infinite_note-0.2.0\src\infinite_note\file
copying src\infinite_note\file\file_manager.py -> infinite_note-0.2.0\src\infinite_note\file
Traceback (most recent call last):
  File "C:\Users\rokan\.virtualenvs\infinite-note-RsPKQUTN\lib\site-packages\pep517\in_process\_in_process.py", line 363, in <module>
    main()
  File "C:\Users\rokan\.virtualenvs\infinite-note-RsPKQUTN\lib\site-packages\pep517\in_process\_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\rokan\.virtualenvs\infinite-note-RsPKQUTN\lib\site-packages\pep517\in_process\_in_process.py", line 314, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\build_meta.py", line 234, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
    self.run_setup()
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\command\sdist.py", line 56, in run
    self.make_distribution()
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\command\sdist.py", line 80, in make_distribution
    orig.sdist.make_distribution(self)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\_distutils\command\sdist.py", line 473, in make_distribution
    self.make_release_tree(base_dir, self.filelist.files)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\command\sdist.py", line 165, in make_release_tree
    self.get_finalized_command('egg_info').save_version_info(dest)
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\command\egg_info.py", line 195, in save_version_info
    edit_config(filename, dict(egg_info=egg_info))
  File "C:\Users\rokan\AppData\Local\Temp\build-env-wmiocxrt\lib\site-packages\setuptools\command\setopt.py", line 43, in edit_config
    opts.read([filename])
  File "C:\Users\rokan\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 698, in read
    self._read(fp, filename)
  File "C:\Users\rokan\AppData\Local\Programs\Python\Python310\lib\configparser.py", line 1021, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 125: illegal multibyte sequence

ERROR Backend subproccess exited when trying to invoke build_sdist
```

**Comment by devrokket** [comment]
맥에서 같은 코드로 빌드시 정상 동작 확인
